name: 'Check for Tag'
description: 'Queries for a git tag using git describe --tags'
author: 'Mark Phippard'
inputs:
  include:
    description: 'Glob pattern of tags to include'
    required: false
    default: '*'
  exclude:
    description:  'Glob pattern of tags to exclude'
    required: false
  commit-ish:
    description: 'Commit-ish object names to describe'
    required: false
    default: 'HEAD~'
  skip-unshallow:
    description: 'Skip the unshallow operation: "true" or "false"'
    required: false
    default: 'false'
  exact-match:
    description: 'Only output exact matches: "true" or "false"'
    required: false
    default: 'false'
  no-tags-text:
    description: 'Text to output if no tags were found'
    required: false
    default: 'NO_TAGS'
outputs:
  tag:
    description: 'The found tag or the value of no-tags-text'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'hash'  
  color: 'blue'
